import java.io.IOException;
import java.io.Reader;
import java.io.StringReader;

import controller.SimulationController;
import model.Simulator;
import model.SimulatorInterface;
import view.SimulationViewInterface;
import view.SimulatorView;

import static org.junit.Assert.assertEquals;

public class SimulationControllerTest2 {


  @org.junit.Test
  public void goEXit() throws IOException {
    StringBuffer out = new StringBuffer();
    Reader in = new StringReader("1\n");
    SimulatorInterface s1 = new Simulator();
    SimulationViewInterface v1 = new SimulatorView();
    SimulationController c1 = new SimulationController(s1, v1, out, in);
    c1.goController();
    assertEquals(out.toString(), "");
  }


  @org.junit.Test
  public void realController() throws IOException {
    StringBuffer out = new StringBuffer();
    Reader in = new StringReader("1\nAA\n3\n1\nAAPL\n2000\n2000"
            + "\n11\n19\n10\nAAPL\n2000\n2000\n11\n20\n10\nb\nb\n6");
    SimulatorInterface s1 = new Simulator();
    SimulationViewInterface v1 = new SimulatorView();
    SimulationController c1 = new SimulationController(s1, v1, out, in);
    c1.goController();
    assertEquals(out.toString(), "\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .buyIndividualStocks\n"
            + "4 .calculateValue\n"
            + "5 .applyStrategy\n"
            + "6 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "********* Welcome to CREATE PORTFOLIO PAGE **********\n"
            + "\n"
            + "TYPE OUT THE NAME OF THE PORTFOLIO YOU DESIRE AND "
            + "PRESS ENTER IF YOU LEAVE IT BLANK IT WILL AUTOMATICALLY BE NAMED\n"
            + "Portfolio AA successfully created\n"
            + "\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .buyIndividualStocks\n"
            + "4 .calculateValue\n"
            + "5 .applyStrategy\n"
            + "6 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "********* Welcome to EDIT PORTFOLIO PAGE **********\n"
            + "1. AA\n"
            + "\n"
            + "ENTER \"B\" TO GO BACK TO MENU\n"
            + "\n"
            + "Enter the index of the portfolio you wanna buy stocks for from the above list\n"
            + "\n"
            + "AA Portfolio selected\n"
            + "\n"
            + "********* Welcome to SINGLE PORTFOLIO PAGE **********\n"
            + "Name: AA\n"
            + "Stocks in Portfolio: \n"
            + "********* Welcome to BUY STOCK PAGE **********\n"
            + "Enter TICKER symbol ?\n"
            + "\n"
            + "Enter the amount you want to invest in stock ? Enter B to go back to Main Menu\n"
            + "\n"
            + "Enter Year you wanna buy the stock ? Enter B to go back to Main Menu\n"
            + "\n"
            + "Enter Month you wanna buy the stock ? Enter B to go back to Main Menu\n"
            + "\n"
            + "Enter day you wanna buy the stock ? Enter B to go back to Main Menu\n"
            + "\n"
            + "Enter commission Enter B to go back to Main Menu\n"
            + "Processing Request ........\n"
            + "Unable to buy stock due error in TICKER, DATE OR NEGATIVE QUANTITY\n"
            + "********* Welcome to BUY STOCK PAGE **********\n"
            + "Enter TICKER symbol ?\n"
            + "\n"
            + "Enter the amount you want to invest in stock ? Enter B to go back to Main Menu\n"
            + "\n"
            + "Enter Year you wanna buy the stock ? Enter B to go back to Main Menu\n"
            + "\n"
            + "Enter Month you wanna buy the stock ? Enter B to go back to Main Menu\n"
            + "\n"
            + "Enter day you wanna buy the stock ? Enter B to go back to Main Menu\n"
            + "\n"
            + "Enter commission Enter B to go back to Main Menu\n"
            + "Processing Request ........Successfully bought stock\n"
            + "\n"
            + "Press y to buy more or n to go back to select a new portfolio\n"
            + "\n"
            + "********* Welcome to EDIT PORTFOLIO PAGE **********\n"
            + "1. AA\n"
            + "\n"
            + "ENTER \"B\" TO GO BACK TO MENU\n"
            + "\n"
            + "Enter the index of the portfolio you wanna buy stocks for from the above list\n"
            + "\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .buyIndividualStocks\n"
            + "4 .calculateValue\n"
            + "5 .applyStrategy\n"
            + "6 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "Thank you for using the application.\n");
  }


  @org.junit.Test
  public void realControllerStrategy() throws IOException {
    StringBuffer out = new StringBuffer();
    Reader in = new StringReader("1\nAA\n5\n1\n1\ny\naapl\ny\namzn"
            + "\nn\ny\n20/11/2000\ny\n12/12/2001\n0\n27\n1000\n2\nb\n6\n");
    SimulatorInterface s1 = new Simulator();
    SimulationViewInterface v1 = new SimulatorView();
    SimulationController c1 = new SimulationController(s1, v1, out, in);
    c1.goController();
    assertEquals(out.toString(), "\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .buyIndividualStocks\n"
            + "4 .calculateValue\n"
            + "5 .applyStrategy\n"
            + "6 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "********* Welcome to CREATE PORTFOLIO PAGE **********\n"
            + "\n"
            + "TYPE OUT THE NAME OF THE PORTFOLIO YOU DESIRE AND "
            + "PRESS ENTER IF YOU LEAVE IT BLANK IT WILL AUTOMATICALLY BE NAMED\n"
            + "Portfolio AA successfully created\n"
            + "\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .buyIndividualStocks\n"
            + "4 .calculateValue\n"
            + "5 .applyStrategy\n"
            + "6 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "********* Welcome to STRATEGY SELECTION PAGE **********\n"
            + "\n"
            + "1. Dollar Cost Averaging\n"
            + "\n"
            + "Enter the index of the strategy you want to apply\n"
            + "\n"
            + "********* Welcome to DISPLAY ALL PORTFOLIO **********\n"
            + "1. AA\n"
            + "\n"
            + "ENTER \"B\" TO GO BACK TO MENU\n"
            + "\n"
            + "********* Welcome to COMPANIES IN THIS PORTFOLIO PAGE **********\n"
            + "\n"
            + "No STOCKS IN PORTTFOLIO\n"
            + "Enter B or b to GO back to Menu\n"
            + "Enter Y to enter new companies\n"
            + "\n"
            + "Enter the ticker single of company you want\n"
            + "\n"
            + "Company successfully added !\n"
            + "\n"
            + "********* Welcome to COMPANIES IN THIS PORTFOLIO PAGE **********\n"
            + "AAPL\n"
            + "\n"
            + "ENTER \"B\" TO GO BACK TO MENU\n"
            + "PRESS Y TO ADD MORE COMPANIES OR N TO PROCEED TO INVEST IN THE ABOVE COMPANIES\n"
            + "\n"
            + "Enter the ticker single of company you want\n"
            + "\n"
            + "Company successfully added !\n"
            + "\n"
            + "********* Welcome to COMPANIES IN THIS PORTFOLIO PAGE **********\n"
            + "AAPL\n"
            + "AMZN\n"
            + "\n"
            + "ENTER \"B\" TO GO BACK TO MENU\n"
            + "PRESS Y TO ADD MORE COMPANIES OR N TO PROCEED TO INVEST IN THE ABOVE COMPANIES\n"
            + "\n"
            + "Enter Y for Preset values of weight and N for custom values and B to go back\n"
            + "\n"
            + "Enter the start date in the format dd/MM/YYYY\n"
            + "\n"
            + "Do you want an end date ? Press Y for yes and N for no\n"
            + "\n"
            + "Enter the end date in the format dd/MM/YYYY\n"
            + "\n"
            + "Enter Commission fee\n"
            + "\n"
            + "Enter Interval in days\n"
            + "\n"
            + "Enter amount to invest\n"
            + "\n"
            + "Successfully executed strategy !\n"
            + "\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .buyIndividualStocks\n"
            + "4 .calculateValue\n"
            + "5 .applyStrategy\n"
            + "6 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "********* Welcome to DISPLAY ALL PORTFOLIO **********\n"
            + "1. Name: AA\n"
            + "Stocks in Portfolio: \n"
            + "Name: AAPL\n"
            + "Total stocks Owned: 27.397260273972602\n"
            + "Date Bought: 2000-11-20\n"
            + "Price: 18.25\n"
            + "Commission Fee: 0.0\n"
            + "\n"
            + "Name: AMZN\n"
            + "Total stocks Owned: 20.0\n"
            + "Date Bought: 2000-11-20\n"
            + "Price: 25.0\n"
            + "Commission Fee: 0.0\n"
            + "\n"
            + "Name: AAPL\n"
            + "Total stocks Owned: 35.86800573888092\n"
            + "Date Bought: 2000-12-18\n"
            + "Price: 13.94\n"
            + "Commission Fee: 0.0\n"
            + "\n"
            + "Name: AMZN\n"
            + "Total stocks Owned: 26.399155227032733\n"
            + "Date Bought: 2000-12-18\n"
            + "Price: 18.94\n"
            + "Commission Fee: 0.0\n"
            + "\n"
            + "Name: AAPL\n"
            + "Total stocks Owned: 29.41176470588235\n"
            + "Date Bought: 2001-01-16\n"
            + "Price: 17.0\n"
            + "Commission Fee: 0.0\n"
            + "\n"
            + "Name: AMZN\n"
            + "Total stocks Owned: 28.985507246376812\n"
            + "Date Bought: 2001-01-16\n"
            + "Price: 17.25\n"
            + "Commission Fee: 0.0\n"
            + "\n"
            + "Name: AAPL\n"
            + "Total stocks Owned: 26.581605528973952\n"
            + "Date Bought: 2001-02-12\n"
            + "Price: 18.81\n"
            + "Commission Fee: 0.0\n"
            + "\n"
            + "Name: AMZN\n"
            + "Total stocks Owned: 36.496350364963504\n"
            + "Date Bought: 2001-02-12\n"
            + "Price: 13.7\n"
            + "Commission Fee: 0.0\n"
            + "\n"
            + "Name: AAPL\n"
            + "Total stocks Owned: 27.59381898454746\n"
            + "Date Bought: 2001-03-12\n"
            + "Price: 18.12\n"
            + "Commission Fee: 0.0\n"
            + "\n"
            + "Name: AMZN\n"
            + "Total stocks Owned: 47.61904761904762\n"
            + "Date Bought: 2001-03-12\n"
            + "Price: 10.5\n"
            + "Commission Fee: 0.0\n"
            + "\n"
            + "Name: AAPL\n"
            + "Total stocks Owned: 24.925224327018945\n"
            + "Date Bought: 2001-04-09\n"
            + "Price: 20.06\n"
            + "Commission Fee: 0.0\n"
            + "\n"
            + "Name: AMZN\n"
            + "Total stocks Owned: 46.728971962616825\n"
            + "Date Bought: 2001-04-09\n"
            + "Price: 10.7\n"
            + "Commission Fee: 0.0\n"
            + "\n"
            + "Name: AAPL\n"
            + "Total stocks Owned: 20.128824476650564\n"
            + "Date Bought: 2001-05-07\n"
            + "Price: 24.84\n"
            + "Commission Fee: 0.0\n"
            + "\n"
            + "Name: AMZN\n"
            + "Total stocks Owned: 30.28467595396729\n"
            + "Date Bought: 2001-05-07\n"
            + "Price: 16.51\n"
            + "Commission Fee: 0.0\n"
            + "\n"
            + "Name: AAPL\n"
            + "Total stocks Owned: 24.437927663734115\n"
            + "Date Bought: 2001-06-04\n"
            + "Price: 20.46\n"
            + "Commission Fee: 0.0\n"
            + "\n"
            + "Name: AMZN\n"
            + "Total stocks Owned: 30.959752321981426\n"
            + "Date Bought: 2001-06-04\n"
            + "Price: 16.15\n"
            + "Commission Fee: 0.0\n"
            + "\n"
            + "Name: AAPL\n"
            + "Total stocks Owned: 21.6076058772688\n"
            + "Date Bought: 2001-07-02\n"
            + "Price: 23.14\n"
            + "Commission Fee: 0.0\n"
            + "\n"
            + "Name: AMZN\n"
            + "Total stocks Owned: 36.101083032490976\n"
            + "Date Bought: 2001-07-02\n"
            + "Price: 13.85\n"
            + "Commission Fee: 0.0\n"
            + "\n"
            + "Name: AAPL\n"
            + "Total stocks Owned: 27.01242571582928\n"
            + "Date Bought: 2001-07-30\n"
            + "Price: 18.51\n"
            + "Commission Fee: 0.0\n"
            + "\n"
            + "Name: AMZN\n"
            + "Total stocks Owned: 41.736227045075125\n"
            + "Date Bought: 2001-07-30\n"
            + "Price: 11.98\n"
            + "Commission Fee: 0.0\n"
            + "\n"
            + "Name: AAPL\n"
            + "Total stocks Owned: 27.53303964757709\n"
            + "Date Bought: 2001-08-27\n"
            + "Price: 18.16\n"
            + "Commission Fee: 0.0\n"
            + "\n"
            + "Name: AMZN\n"
            + "Total stocks Owned: 50.45408678102926\n"
            + "Date Bought: 2001-08-27\n"
            + "Price: 9.91\n"
            + "Commission Fee: 0.0\n"
            + "\n"
            + "Name: AAPL\n"
            + "Total stocks Owned: 31.347962382445143\n"
            + "Date Bought: 2001-09-24\n"
            + "Price: 15.95\n"
            + "Commission Fee: 0.0\n"
            + "\n"
            + "Name: AMZN\n"
            + "Total stocks Owned: 68.11989100817439\n"
            + "Date Bought: 2001-09-24\n"
            + "Price: 7.34\n"
            + "Commission Fee: 0.0\n"
            + "\n"
            + "Name: AAPL\n"
            + "Total stocks Owned: 27.63957987838585\n"
            + "Date Bought: 2001-10-22\n"
            + "Price: 18.09\n"
            + "Commission Fee: 0.0\n"
            + "\n"
            + "Name: AMZN\n"
            + "Total stocks Owned: 62.18905472636816\n"
            + "Date Bought: 2001-10-22\n"
            + "Price: 8.04\n"
            + "Commission Fee: 0.0\n"
            + "\n"
            + "Name: AAPL\n"
            + "Total stocks Owned: 26.371308016877634\n"
            + "Date Bought: 2001-11-19\n"
            + "Price: 18.96\n"
            + "Commission Fee: 0.0\n"
            + "\n"
            + "Name: AMZN\n"
            + "Total stocks Owned: 55.55555555555556\n"
            + "Date Bought: 2001-11-19\n"
            + "Price: 9.0\n"
            + "Commission Fee: 0.0\n"
            + "\n"
            + "\n"
            + "\n"
            + "ENTER \"B\" TO GO BACK TO MENU\n"
            + "\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .buyIndividualStocks\n"
            + "4 .calculateValue\n"
            + "5 .applyStrategy\n"
            + "6 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "Thank you for using the application.");
  }

}
