import java.io.IOException;
import java.io.Reader;
import java.io.StringReader;

import controller.SimulationController;
import model.Simulator;
import model.SimulatorInterface;
import view.SimulationViewInterface;
import view.SimulatorView;

import static org.junit.Assert.assertEquals;

public class SimulationControllerTest {

  @org.junit.Test
  public void goEXit() throws IOException {
    StringBuffer out = new StringBuffer();
    Reader in = new StringReader("C1\nq\nO1\n5\n");
    SimulatorInterface s1 = new Simulator();
    SimulationViewInterface v1 = new SimulatorView();
    SimulationController c1 = new SimulationController(s1, v1, out, in);
    c1.goController();
    assertEquals("\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .editPortfolio\n"
            + "4 .calculateValue\n"
            + "5 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "Error in input please try again.\n"
            + "Error in input please try again.\n"
            + "Error in input please try again.\n"
            + "\n"
            + "Thank you for using the application.\n", out.toString());

  }

  @org.junit.Test
  public void goDisplayAllPortfolios() throws IOException {

    StringBuffer out = new StringBuffer();
    //Reader in = new StringReader("C1\nq\nO1\n2\nQ\n2\n5\nb\n5\n");
    Reader in = new StringReader("2\nb\n5\n");
    SimulatorInterface s1 = new Simulator();
    SimulationViewInterface v1 = new SimulatorView();
    SimulationController c1 = new SimulationController(s1, v1, out, in);
    c1.goController();
    assertEquals("\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .editPortfolio\n"
            + "4 .calculateValue\n"
            + "5 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "********* Welcome to DISPLAY ALL PORTFOLIO **********\n"
            + "\n"
            + "No portfolio created\n"
            + "Enter B or b to GO back to Menu\n"
            + "\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .editPortfolio\n"
            + "4 .calculateValue\n"
            + "5 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "Thank you for using the application.\n", out.toString());

  }

  @org.junit.Test
  public void createPortfolioPortfolios() throws IOException {

    StringBuffer out = new StringBuffer();
    //Reader in = new StringReader("C1\nq\nO1\n2\nQ\n2\n5\nb\n5\n");
    Reader in = new StringReader("1\nRetirement\n2\nb\n5\n");
    SimulatorInterface s1 = new Simulator();
    SimulationViewInterface v1 = new SimulatorView();
    SimulationController c1 = new SimulationController(s1, v1, out, in);
    c1.goController();
    assertEquals("\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .editPortfolio\n"
            + "4 .calculateValue\n"
            + "5 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "********* Welcome to CREATE PORTFOLIO PAGE **********\n"
            + "\n"
            + "TYPE OUT THE NAME OF THE PORTFOLIO YOU DESIRE AND "
            + "PRESS ENTER IF YOU LEAVE IT BLANK IT WILL AUTOMATICALLY BE NAMED\n"
            + "Portfolio Retirement successfully created\n"
            + "\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .editPortfolio\n"
            + "4 .calculateValue\n"
            + "5 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "********* Welcome to DISPLAY ALL PORTFOLIO **********\n"
            + "1. Name: Retirement\n"
            + "Stocks in Portfolio: \n"
            + "\n"
            + "\n"
            + "ENTER \"B\" TO GO BACK TO MENU\n"
            + "\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .editPortfolio\n"
            + "4 .calculateValue\n"
            + "5 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "Thank you for using the application.\n", out.toString());


  }


  @org.junit.Test
  public void correctBuyingStock() throws IOException {

    StringBuffer out = new StringBuffer();
    //Reader in = new StringReader("C1\nq\nO1\n2\nQ\n2\n5\nb\n5\n");
    Reader in = new StringReader("1\n\n3\n1\nAAPL\n12\n2000\n1\n4\nn\nb\n5");
    SimulatorInterface s1 = new Simulator();
    SimulationViewInterface v1 = new SimulatorView();
    SimulationController c1 = new SimulationController(s1, v1, out, in);
    c1.goController();
    assertEquals("\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .editPortfolio\n"
            + "4 .calculateValue\n"
            + "5 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "********* Welcome to CREATE PORTFOLIO PAGE **********\n"
            + "\n"
            + "TYPE OUT THE NAME OF THE PORTFOLIO YOU DESIRE AND PRESS ENTER IF YOU LEAVE IT"
            + " BLANK IT WILL AUTOMATICALLY BE NAMED\n"
            + "Portfolio  successfully created\n"
            + "\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .editPortfolio\n"
            + "4 .calculateValue\n"
            + "5 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "********* Welcome to EDIT PORTFOLIO PAGE **********\n"
            + "1. Name: Portfolio 1\n"
            + "Stocks in Portfolio: \n"
            + "\n"
            + "\n"
            + "ENTER \"B\" TO GO BACK TO MENU\n"
            + "\n"
            + "Enter the index of the portfolio you wanna edit from the above list\n"
            + "\n"
            + " Portfolio selected\n"
            + "\n"
            + "********* Welcome to SINGLE PORTFOLIO PAGE **********\n"
            + "Name: Portfolio 1\n"
            + "Stocks in Portfolio: \n"
            + "********* Welcome to BUY STOCK PAGE **********\n"
            + "Enter TICKER symbol ?\n"
            + "\n"
            + "Enter quantity of stock you want to buy ? Enter B to go back to Main Menu\n"
            + "\n"
            + "Enter Year you wanna buy the stock ? Enter B to go back to Main Menu\n"
            + "\n"
            + "Enter Month you wanna buy the stock ? Enter B to go back to Main Menu\n"
            + "\n"
            + "Enter day you wanna buy the stock ? Enter B to go back to Main Menu\n"
            + "Processing Request ........Successfully bought stock\n"
            + "\n"
            + "Press y to buy more or n to go back to select a new portfolio\n"
            + "\n"
            + "********* Welcome to EDIT PORTFOLIO PAGE **********\n"
            + "1. Name: Portfolio 1\n"
            + "Stocks in Portfolio: \n"
            + "Name: AAPL\n"
            + "Total stocks Owned: 12\n"
            + "Date Bought: 2000-01-04\n"
            + "Price: 101.19\n"
            + "\n"
            + "\n"
            + "\n"
            + "ENTER \"B\" TO GO BACK TO MENU\n"
            + "\n"
            + "Enter the index of the portfolio you wanna edit from the above list\n"
            + "\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .editPortfolio\n"
            + "4 .calculateValue\n"
            + "5 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "Thank you for using the application.\n", out.toString());

  }

  @org.junit.Test
  public void negativeNumberBuyingStock() throws IOException {

    StringBuffer out = new StringBuffer();
    //Reader in = new StringReader("C1\nq\nO1\n2\nQ\n2\n5\nb\n5\n");
    Reader in = new StringReader("1\n\n3\n1\nAAPL\n-5\n2000\n1\n4\nn\nb\n5");
    SimulatorInterface s1 = new Simulator();
    SimulationViewInterface v1 = new SimulatorView();
    SimulationController c1 = new SimulationController(s1, v1, out, in);
    c1.goController();
    assertEquals("\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .editPortfolio\n"
            + "4 .calculateValue\n"
            + "5 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "********* Welcome to CREATE PORTFOLIO PAGE **********\n"
            + "\n"
            + "TYPE OUT THE NAME OF THE PORTFOLIO YOU DESIRE AND "
            + "PRESS ENTER IF YOU LEAVE IT BLANK IT WILL AUTOMATICALLY BE NAMED\n"
            + "Portfolio  successfully created\n"
            + "\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .editPortfolio\n"
            + "4 .calculateValue\n"
            + "5 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "********* Welcome to EDIT PORTFOLIO PAGE **********\n"
            + "1. Name: Portfolio 1\n"
            + "Stocks in Portfolio: \n"
            + "\n"
            + "\n"
            + "ENTER \"B\" TO GO BACK TO MENU\n"
            + "\n"
            + "Enter the index of the portfolio you wanna edit from the above list\n"
            + "\n"
            + " Portfolio selected\n"
            + "\n"
            + "********* Welcome to SINGLE PORTFOLIO PAGE **********\n"
            + "Name: Portfolio 1\n"
            + "Stocks in Portfolio: \n"
            + "********* Welcome to BUY STOCK PAGE **********\n"
            + "Enter TICKER symbol ?\n"
            + "\n"
            + "Enter quantity of stock you want to buy ? Enter B to go back to Main Menu\n"
            + "\n"
            + "Enter Year you wanna buy the stock ? Enter B to go back to Main Menu\n"
            + "\n"
            + "Enter Month you wanna buy the stock ? Enter B to go back to Main Menu\n"
            + "\n"
            + "Enter day you wanna buy the stock ? Enter B to go back to Main Menu\n"
            + "Processing Request ........\n"
            + "Unable to buy stock due error in TICKER, DATE OR NEGATIVE QUANTITY\n"
            + "********* Welcome to BUY STOCK PAGE **********\n"
            + "Enter TICKER symbol ?\n"
            + "\n"
            + "Enter quantity of stock you want to buy ? Enter B to go back to Main Menu\n"
            + "\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .editPortfolio\n"
            + "4 .calculateValue\n"
            + "5 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "Thank you for using the application.\n", out.toString());
  }

  @org.junit.Test
  public void weekendBuyingStock() throws IOException {
    StringBuffer out = new StringBuffer();
    //Reader in = new StringReader("C1\nq\nO1\n2\nQ\n2\n5\nb\n5\n");
    Reader in = new StringReader("1\n\n3\n1\nAAPL\n5\n2018\n11\n11\nn\nb\n5");
    SimulatorInterface s1 = new Simulator();
    SimulationViewInterface v1 = new SimulatorView();
    SimulationController c1 = new SimulationController(s1, v1, out, in);
    c1.goController();
    assertEquals("\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .editPortfolio\n"
            + "4 .calculateValue\n"
            + "5 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "********* Welcome to CREATE PORTFOLIO PAGE **********\n"
            + "\n"
            + "TYPE OUT THE NAME OF THE PORTFOLIO YOU DESIRE AND PRESS "
            + "ENTER IF YOU LEAVE IT BLANK IT WILL AUTOMATICALLY BE NAMED\n"
            + "Portfolio  successfully created\n"
            + "\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .editPortfolio\n"
            + "4 .calculateValue\n"
            + "5 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "********* Welcome to EDIT PORTFOLIO PAGE **********\n"
            + "1. Name: Portfolio 1\n"
            + "Stocks in Portfolio: \n"
            + "\n"
            + "\n"
            + "ENTER \"B\" TO GO BACK TO MENU\n"
            + "\n"
            + "Enter the index of the portfolio you wanna edit from the above list\n"
            + "\n"
            + " Portfolio selected\n"
            + "\n"
            + "********* Welcome to SINGLE PORTFOLIO PAGE **********\n"
            + "Name: Portfolio 1\n"
            + "Stocks in Portfolio: \n"
            + "********* Welcome to BUY STOCK PAGE **********\n"
            + "Enter TICKER symbol ?\n"
            + "\n"
            + "Enter quantity of stock you want to buy ? Enter B to go back to Main Menu\n"
            + "\n"
            + "Enter Year you wanna buy the stock ? Enter B to go back to Main Menu\n"
            + "\n"
            + "Enter Month you wanna buy the stock ? Enter B to go back to Main Menu\n"
            + "\n"
            + "Enter day you wanna buy the stock ? Enter B to go back to Main Menu\n"
            + "Processing Request ........\n"
            + "Unable to buy stock due error in TICKER, DATE OR NEGATIVE QUANTITY\n"
            + "********* Welcome to BUY STOCK PAGE **********\n"
            + "Enter TICKER symbol ?\n"
            + "\n"
            + "Enter quantity of stock you want to buy ? Enter B to go back to Main Menu\n"
            + "\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .editPortfolio\n"
            + "4 .calculateValue\n"
            + "5 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "Thank you for using the application.", out.toString());

  }

  @org.junit.Test
  public void publicHolidayBuyingStock() throws IOException {
    StringBuffer out = new StringBuffer();
    //Reader in = new StringReader("C1\nq\nO1\n2\nQ\n2\n5\nb\n5\n");
    Reader in = new StringReader("1\n\n3\n1\nAAPL\n5\n2017\n12\n25\nn\nb\n5");
    SimulatorInterface s1 = new Simulator();
    SimulationViewInterface v1 = new SimulatorView();
    SimulationController c1 = new SimulationController(s1, v1, out, in);
    c1.goController();
    assertEquals("\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .editPortfolio\n"
            + "4 .calculateValue\n"
            + "5 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "********* Welcome to CREATE PORTFOLIO PAGE **********\n"
            + "\n"
            + "TYPE OUT THE NAME OF THE PORTFOLIO YOU DESIRE AND PRESS "
            + "ENTER IF YOU LEAVE IT BLANK IT WILL AUTOMATICALLY BE NAMED\n"
            + "Portfolio  successfully created\n"
            + "\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .editPortfolio\n"
            + "4 .calculateValue\n"
            + "5 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "********* Welcome to EDIT PORTFOLIO PAGE **********\n"
            + "1. Name: Portfolio 1\n"
            + "Stocks in Portfolio: \n"
            + "\n"
            + "\n"
            + "ENTER \"B\" TO GO BACK TO MENU\n"
            + "\n"
            + "Enter the index of the portfolio you wanna edit from the above list\n"
            + "\n"
            + " Portfolio selected\n"
            + "\n"
            + "********* Welcome to SINGLE PORTFOLIO PAGE **********\n"
            + "Name: Portfolio 1\n"
            + "Stocks in Portfolio: \n"
            + "********* Welcome to BUY STOCK PAGE **********\n"
            + "Enter TICKER symbol ?\n"
            + "\n"
            + "Enter quantity of stock you want to buy ? Enter B to go back to Main Menu\n"
            + "\n"
            + "Enter Year you wanna buy the stock ? Enter B to go back to Main Menu\n"
            + "\n"
            + "Enter Month you wanna buy the stock ? Enter B to go back to Main Menu\n"
            + "\n"
            + "Enter day you wanna buy the stock ? Enter B to go back to Main Menu\n"
            + "Processing Request ........\n"
            + "Unable to buy stock due error in TICKER, DATE OR NEGATIVE QUANTITY\n"
            + "********* Welcome to BUY STOCK PAGE **********\n"
            + "Enter TICKER symbol ?\n"
            + "\n"
            + "Enter quantity of stock you want to buy ? Enter B to go back to Main Menu\n"
            + "\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .editPortfolio\n"
            + "4 .calculateValue\n"
            + "5 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "Thank you for using the application.\n", out.toString());
  }

  @org.junit.Test
  public void wrongDateFormatBuyingStock() throws IOException {
    StringBuffer out = new StringBuffer();
    //Reader in = new StringReader("C1\nq\nO1\n2\nQ\n2\n5\nb\n5\n");
    Reader in = new StringReader("1\n\n3\n1\nAAPL\n5\n20017\n12\n25\nn\nb\n5");
    SimulatorInterface s1 = new Simulator();
    SimulationViewInterface v1 = new SimulatorView();
    SimulationController c1 = new SimulationController(s1, v1, out, in);
    c1.goController();
    assertEquals("\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .editPortfolio\n"
            + "4 .calculateValue\n"
            + "5 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "********* Welcome to CREATE PORTFOLIO PAGE **********\n"
            + "\n"
            + "TYPE OUT THE NAME OF THE PORTFOLIO YOU DESIRE AND PRESS "
            + "ENTER IF YOU LEAVE IT BLANK IT WILL AUTOMATICALLY BE NAMED\n"
            + "Portfolio  successfully created\n"
            + "\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .editPortfolio\n"
            + "4 .calculateValue\n"
            + "5 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "********* Welcome to EDIT PORTFOLIO PAGE **********\n"
            + "1. Name: Portfolio 1\n"
            + "Stocks in Portfolio: \n"
            + "\n"
            + "\n"
            + "ENTER \"B\" TO GO BACK TO MENU\n"
            + "\n"
            + "Enter the index of the portfolio you wanna edit from the above list\n"
            + "\n"
            + " Portfolio selected\n"
            + "\n"
            + "********* Welcome to SINGLE PORTFOLIO PAGE **********\n"
            + "Name: Portfolio 1\n"
            + "Stocks in Portfolio: \n"
            + "********* Welcome to BUY STOCK PAGE **********\n"
            + "Enter TICKER symbol ?\n"
            + "\n"
            + "Enter quantity of stock you want to buy ? Enter B to go back to Main Menu\n"
            + "\n"
            + "Enter Year you wanna buy the stock ? Enter B to go back to Main Menu\n"
            + "\n"
            + "Enter Month you wanna buy the stock ? Enter B to go back to Main Menu\n"
            + "\n"
            + "Enter day you wanna buy the stock ? Enter B to go back to Main Menu\n"
            + "Processing Request ........\n"
            + "Unable to buy stock due error in TICKER, DATE OR NEGATIVE QUANTITY\n"
            + "********* Welcome to BUY STOCK PAGE **********\n"
            + "Enter TICKER symbol ?\n"
            + "\n"
            + "Enter quantity of stock you want to buy ? Enter B to go back to Main Menu\n"
            + "\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .editPortfolio\n"
            + "4 .calculateValue\n"
            + "5 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "Thank you for using the application.\n", out.toString());
  }

  @org.junit.Test
  public void wrongTickerBuyingStock() throws IOException {
    StringBuffer out = new StringBuffer();
    //Reader in = new StringReader("C1\nq\nO1\n2\nQ\n2\n5\nb\n5\n");
    Reader in = new StringReader("1\n\n3\n1\nAAPLe\n5\n2017\n12\n25\nn\nb\n5");
    SimulatorInterface s1 = new Simulator();
    SimulationViewInterface v1 = new SimulatorView();
    SimulationController c1 = new SimulationController(s1, v1, out, in);
    c1.goController();
    assertEquals("\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .editPortfolio\n"
            + "4 .calculateValue\n"
            + "5 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "********* Welcome to CREATE PORTFOLIO PAGE **********\n"
            + "\n"
            + "TYPE OUT THE NAME OF THE PORTFOLIO YOU DESIRE AND PRESS "
            + "ENTER IF YOU LEAVE IT BLANK IT WILL AUTOMATICALLY BE NAMED\n"
            + "Portfolio  successfully created\n"
            + "\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .editPortfolio\n"
            + "4 .calculateValue\n"
            + "5 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "********* Welcome to EDIT PORTFOLIO PAGE **********\n"
            + "1. Name: Portfolio 1\n"
            + "Stocks in Portfolio: \n"
            + "\n"
            + "\n"
            + "ENTER \"B\" TO GO BACK TO MENU\n"
            + "\n"
            + "Enter the index of the portfolio you wanna edit from the above list\n"
            + "\n"
            + " Portfolio selected\n"
            + "\n"
            + "********* Welcome to SINGLE PORTFOLIO PAGE **********\n"
            + "Name: Portfolio 1\n"
            + "Stocks in Portfolio: \n"
            + "********* Welcome to BUY STOCK PAGE **********\n"
            + "Enter TICKER symbol ?\n"
            + "\n"
            + "Enter quantity of stock you want to buy ? Enter B to go back to Main Menu\n"
            + "\n"
            + "Enter Year you wanna buy the stock ? Enter B to go back to Main Menu\n"
            + "\n"
            + "Enter Month you wanna buy the stock ? Enter B to go back to Main Menu\n"
            + "\n"
            + "Enter day you wanna buy the stock ? Enter B to go back to Main Menu\n"
            + "Processing Request ........\n"
            + "Unable to buy stock due error in TICKER, DATE OR NEGATIVE QUANTITY\n"
            + "********* Welcome to BUY STOCK PAGE **********\n"
            + "Enter TICKER symbol ?\n"
            + "\n"
            + "Enter quantity of stock you want to buy ? Enter B to go back to Main Menu\n"
            + "\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .editPortfolio\n"
            + "4 .calculateValue\n"
            + "5 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "Thank you for using the application.\n", out.toString());
  }

  /**
   * Test for finding costbasis after stock is bought.
   *
   * @throws IOException for Appendable.
   */
  @org.junit.Test
  public void costBasisCorrect() throws IOException {
    StringBuffer out = new StringBuffer();
    //Reader in = new StringReader("C1\nq\nO1\n2\nQ\n2\n5\nb\n5\n");
    Reader in = new StringReader("1\n\n3\n1\nAAPL\n5\n2000\n1\n4"
            + "\nn\nb\n4\n1\n1\n2018\n11\n14\nb\nb\n5");
    SimulatorInterface s1 = new Simulator();
    SimulationViewInterface v1 = new SimulatorView();
    SimulationController c1 = new SimulationController(s1, v1, out, in);
    c1.goController();
    assertEquals("Enter the index of the portfolio you wanna calculate "
            + "values for from the above pics and B to go back to menu\n"
            + "\n"
            + " Portfolio selected\n"
            + "\n"
            + "********* Welcome to SINGLE PORTFOLIO PAGE **********\n"
            + "Name: Portfolio 1\n"
            + "Stocks in Portfolio: \n"
            + "Name: AAPL\n"
            + "Total stocks Owned: 5\n"
            + "Date Bought: 2000-01-04\n"
            + "Price: 101.19\n"
            + "\n"
            + "\n"
            + "********* Welcome to CALCULATE VALUE PAGE **********\n"
            + "\n"
            + " PRESS 1 FOR COST BASIS\n"
            + "PRESS 2 FOR PORTFOLIO VALUE\n"
            + " PRESS B TO GO BACK\n"
            + "\n"
            + "Enter Year you wanna calculate for\n"
            + "\n"
            + "Enter Month you wanna calculate for\n"
            + "\n"
            + "Enter day you wanna calculate for\n"
            + "\n"
            + "THE COST BASIS OF THIS PORTFOLIO IS 505.95\n"
            + "\n"
            + "********* Welcome to CALCULATE VALUE PAGE **********\n"
            + "\n"
            + " PRESS 1 FOR COST BASIS\n"
            + "PRESS 2 FOR PORTFOLIO VALUE\n"
            + " PRESS B TO GO BACK\n"
            + "\n"
            + "********* Welcome to DISPLAY ALL PORTFOLIO **********\n"
            + "1. Name: Portfolio 1\n"
            + "Stocks in Portfolio: \n"
            + "Name: AAPL\n"
            + "Total stocks Owned: 5\n"
            + "Date Bought: 2000-01-04\n"
            + "Price: 101.19\n"
            + "\n"
            + "\n"
            + "\n"
            + "ENTER \"B\" TO GO BACK TO MENU\n"
            + "\n"
            + "Enter the index of the portfolio you wanna calculate "
            + "values for from the above pics and B to go back to menu\n"
            + "\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .editPortfolio\n"
            + "4 .calculateValue\n"
            + "5 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "Thank you for using the application.", out.toString());
  }


  /**
   * Test for finding costbasis before stock is bought.
   *
   * @throws IOException for Appendable.
   */
  @org.junit.Test
  public void costBasisWrong() throws IOException {
    StringBuffer out = new StringBuffer();
    //Reader in = new StringReader("C1\nq\nO1\n2\nQ\n2\n5\nb\n5\n");
    Reader in = new StringReader("1\n\n3\n1\nAAPL\n5\n2000\n1"
            + "\n4\nn\nb\n4\n1\n1\n1999\n11\n14\nb\nb\n5");
    SimulatorInterface s1 = new Simulator();
    SimulationViewInterface v1 = new SimulatorView();
    SimulationController c1 = new SimulationController(s1, v1, out, in);
    c1.goController();
    assertEquals("\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .editPortfolio\n"
            + "4 .calculateValue\n"
            + "5 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "********* Welcome to CREATE PORTFOLIO PAGE **********\n"
            + "\n"
            + "TYPE OUT THE NAME OF THE PORTFOLIO YOU DESIRE AND PRESS "
            + "ENTER IF YOU LEAVE IT BLANK IT WILL AUTOMATICALLY BE NAMED\n"
            + "Portfolio  successfully created\n"
            + "\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .editPortfolio\n"
            + "4 .calculateValue\n"
            + "5 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "********* Welcome to EDIT PORTFOLIO PAGE **********\n"
            + "1. Name: Portfolio 1\n"
            + "Stocks in Portfolio: \n"
            + "\n"
            + "\n"
            + "ENTER \"B\" TO GO BACK TO MENU\n"
            + "\n"
            + "Enter the index of the portfolio you wanna edit from the above list\n"
            + "\n"
            + " Portfolio selected\n"
            + "\n"
            + "********* Welcome to SINGLE PORTFOLIO PAGE **********\n"
            + "Name: Portfolio 1\n"
            + "Stocks in Portfolio: \n"
            + "********* Welcome to BUY STOCK PAGE **********\n"
            + "Enter TICKER symbol ?\n"
            + "\n"
            + "Enter quantity of stock you want to buy ? Enter B to go back to Main Menu\n"
            + "\n"
            + "Enter Year you wanna buy the stock ? Enter B to go back to Main Menu\n"
            + "\n"
            + "Enter Month you wanna buy the stock ? Enter B to go back to Main Menu\n"
            + "\n"
            + "Enter day you wanna buy the stock ? Enter B to go back to Main Menu\n"
            + "Processing Request ........Successfully bought stock\n"
            + "\n"
            + "Press y to buy more or n to go back to select a new portfolio\n"
            + "\n"
            + "********* Welcome to EDIT PORTFOLIO PAGE **********\n"
            + "1. Name: Portfolio 1\n"
            + "Stocks in Portfolio: \n"
            + "Name: AAPL\n"
            + "Total stocks Owned: 5\n"
            + "Date Bought: 2000-01-04\n"
            + "Price: 101.19\n"
            + "\n"
            + "\n"
            + "\n"
            + "ENTER \"B\" TO GO BACK TO MENU\n"
            + "\n"
            + "Enter the index of the portfolio you wanna edit from the above list\n"
            + "\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .editPortfolio\n"
            + "4 .calculateValue\n"
            + "5 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "********* Welcome to DISPLAY ALL PORTFOLIO **********\n"
            + "1. Name: Portfolio 1\n"
            + "Stocks in Portfolio: \n"
            + "Name: AAPL\n"
            + "Total stocks Owned: 5\n"
            + "Date Bought: 2000-01-04\n"
            + "Price: 101.19\n"
            + "\n"
            + "\n"
            + "\n"
            + "ENTER \"B\" TO GO BACK TO MENU\n"
            + "\n"
            + "Enter the index of the portfolio you wanna calculate "
            + "values for from the above pics and B to go back to menu\n"
            + "\n"
            + " Portfolio selected\n"
            + "\n"
            + "********* Welcome to SINGLE PORTFOLIO PAGE **********\n"
            + "Name: Portfolio 1\n"
            + "Stocks in Portfolio: \n"
            + "Name: AAPL\n"
            + "Total stocks Owned: 5\n"
            + "Date Bought: 2000-01-04\n"
            + "Price: 101.19\n"
            + "\n"
            + "\n"
            + "********* Welcome to CALCULATE VALUE PAGE **********\n"
            + "\n"
            + " PRESS 1 FOR COST BASIS\n"
            + "PRESS 2 FOR PORTFOLIO VALUE\n"
            + " PRESS B TO GO BACK\n"
            + "\n"
            + "Enter Year you wanna calculate for\n"
            + "\n"
            + "Enter Month you wanna calculate for\n"
            + "\n"
            + "Enter day you wanna calculate for\n"
            + "\n"
            + "THE COST BASIS OF THIS PORTFOLIO IS 0.0\n"
            + "\n"
            + "********* Welcome to CALCULATE VALUE PAGE **********\n"
            + "\n"
            + " PRESS 1 FOR COST BASIS\n"
            + "PRESS 2 FOR PORTFOLIO VALUE\n"
            + " PRESS B TO GO BACK\n"
            + "\n"
            + "********* Welcome to DISPLAY ALL PORTFOLIO **********\n"
            + "1. Name: Portfolio 1\n"
            + "Stocks in Portfolio: \n"
            + "Name: AAPL\n"
            + "Total stocks Owned: 5\n"
            + "Date Bought: 2000-01-04\n"
            + "Price: 101.19\n"
            + "\n"
            + "\n"
            + "\n"
            + "ENTER \"B\" TO GO BACK TO MENU\n"
            + "\n"
            + "Enter the index of the portfolio you wanna calculate "
            + "values for from the above pics and B to go back to menu\n"
            + "\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .editPortfolio\n"
            + "4 .calculateValue\n"
            + "5 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "Thank you for using the application.\n", out.toString());
  }


  /**
   * Test for finding portfolio before stock is bought.
   *
   * @throws IOException for Appendable.
   */
  @org.junit.Test
  public void portFolioWrong() throws IOException {
    StringBuffer out = new StringBuffer();
    //Reader in = new StringReader("C1\nq\nO1\n2\nQ\n2\n5\nb\n5\n");
    Reader in = new StringReader("1\n\n3\n1\nAAPL\n5\n2000\n1\n4"
            + "\nn\nb\n4\n1\n2\n1999\n11\n14\nb\nb\n5");
    SimulatorInterface s1 = new Simulator();
    SimulationViewInterface v1 = new SimulatorView();
    SimulationController c1 = new SimulationController(s1, v1, out, in);
    c1.goController();
    assertEquals("\n"
            + "Enter the index of the portfolio you wanna edit from the above list\n"
            + "\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .editPortfolio\n"
            + "4 .calculateValue\n"
            + "5 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "********* Welcome to DISPLAY ALL PORTFOLIO **********\n"
            + "1. Name: Portfolio 1\n"
            + "Stocks in Portfolio: \n"
            + "Name: AAPL\n"
            + "Total stocks Owned: 5\n"
            + "Date Bought: 2000-01-04\n"
            + "Price: 101.19\n"
            + "\n"
            + "\n"
            + "\n"
            + "ENTER \"B\" TO GO BACK TO MENU\n"
            + "\n"
            + "Enter the index of the portfolio you wanna calculate values "
            + "for from the above pics and B to go back to menu\n"
            + "\n"
            + " Portfolio selected\n"
            + "\n"
            + "********* Welcome to SINGLE PORTFOLIO PAGE **********\n"
            + "Name: Portfolio 1\n"
            + "Stocks in Portfolio: \n"
            + "Name: AAPL\n"
            + "Total stocks Owned: 5\n"
            + "Date Bought: 2000-01-04\n"
            + "Price: 101.19\n"
            + "\n"
            + "\n"
            + "********* Welcome to CALCULATE VALUE PAGE **********\n"
            + "\n"
            + " PRESS 1 FOR COST BASIS\n"
            + "PRESS 2 FOR PORTFOLIO VALUE\n"
            + " PRESS B TO GO BACK\n"
            + "\n"
            + "Enter Year you wanna calculate for\n"
            + "\n"
            + "Enter Month you wanna calculate for\n"
            + "\n"
            + "Enter day you wanna calculate for\n"
            + "\n"
            + "THE PORTFOLIO VALUE OF THIS PORTFOLIO IS 0.0\n"
            + "\n"
            + "********* Welcome to CALCULATE VALUE PAGE **********\n"
            + "\n"
            + " PRESS 1 FOR COST BASIS\n"
            + "PRESS 2 FOR PORTFOLIO VALUE\n"
            + " PRESS B TO GO BACK\n"
            + "\n"
            + "********* Welcome to DISPLAY ALL PORTFOLIO **********\n"
            + "1. Name: Portfolio 1\n"
            + "Stocks in Portfolio: \n"
            + "Name: AAPL\n"
            + "Total stocks Owned: 5\n"
            + "Date Bought: 2000-01-04\n"
            + "Price: 101.19\n"
            + "\n"
            + "\n"
            + "\n"
            + "ENTER \"B\" TO GO BACK TO MENU\n"
            + "\n"
            + "Enter the index of the portfolio you wanna calculate values "
            + "for from the above pics and B to go back to menu\n"
            + "\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .editPortfolio\n"
            + "4 .calculateValue\n"
            + "5 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "Thank you for using the application.\n", out.toString());
  }

  /**
   * Test for finding portfolio after stock is bought.
   *
   * @throws IOException for Appendable.
   */
  @org.junit.Test
  public void portFolioCorrect() throws IOException {
    StringBuffer out = new StringBuffer();
    //Reader in = new StringReader("C1\nq\nO1\n2\nQ\n2\n5\nb\n5\n");
    Reader in = new StringReader("1\n\n3\n1\nAAPL\n5\n2000\n1\n4"
            + "\nn\nb\n4\n1\n2\n2018\n11\n14\nb\nb\n5");
    SimulatorInterface s1 = new Simulator();
    SimulationViewInterface v1 = new SimulatorView();
    SimulationController c1 = new SimulationController(s1, v1, out, in);
    c1.goController();
    assertEquals("\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .editPortfolio\n"
            + "4 .calculateValue\n"
            + "5 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "********* Welcome to CREATE PORTFOLIO PAGE **********\n"
            + "\n"
            + "TYPE OUT THE NAME OF THE PORTFOLIO YOU DESIRE AND PRESS "
            + "ENTER IF YOU LEAVE IT BLANK IT WILL AUTOMATICALLY BE NAMED\n"
            + "Portfolio  successfully created\n"
            + "\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .editPortfolio\n"
            + "4 .calculateValue\n"
            + "5 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "********* Welcome to EDIT PORTFOLIO PAGE **********\n"
            + "1. Name: Portfolio 1\n"
            + "Stocks in Portfolio: \n"
            + "\n"
            + "\n"
            + "ENTER \"B\" TO GO BACK TO MENU\n"
            + "\n"
            + "Enter the index of the portfolio you wanna edit from the above list\n"
            + "\n"
            + " Portfolio selected\n"
            + "\n"
            + "********* Welcome to SINGLE PORTFOLIO PAGE **********\n"
            + "Name: Portfolio 1\n"
            + "Stocks in Portfolio: \n"
            + "********* Welcome to BUY STOCK PAGE **********\n"
            + "Enter TICKER symbol ?\n"
            + "\n"
            + "Enter quantity of stock you want to buy ? Enter B to go back to Main Menu\n"
            + "\n"
            + "Enter Year you wanna buy the stock ? Enter B to go back to Main Menu\n"
            + "\n"
            + "Enter Month you wanna buy the stock ? Enter B to go back to Main Menu\n"
            + "\n"
            + "Enter day you wanna buy the stock ? Enter B to go back to Main Menu\n"
            + "Processing Request ........Successfully bought stock\n"
            + "\n"
            + "Press y to buy more or n to go back to select a new portfolio\n"
            + "\n"
            + "********* Welcome to EDIT PORTFOLIO PAGE **********\n"
            + "1. Name: Portfolio 1\n"
            + "Stocks in Portfolio: \n"
            + "Name: AAPL\n"
            + "Total stocks Owned: 5\n"
            + "Date Bought: 2000-01-04\n"
            + "Price: 101.19\n"
            + "\n"
            + "\n"
            + "\n"
            + "ENTER \"B\" TO GO BACK TO MENU\n"
            + "\n"
            + "Enter the index of the portfolio you wanna edit from the above list\n"
            + "\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .editPortfolio\n"
            + "4 .calculateValue\n"
            + "5 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "********* Welcome to DISPLAY ALL PORTFOLIO **********\n"
            + "1. Name: Portfolio 1\n"
            + "Stocks in Portfolio: \n"
            + "Name: AAPL\n"
            + "Total stocks Owned: 5\n"
            + "Date Bought: 2000-01-04\n"
            + "Price: 101.19\n"
            + "\n"
            + "\n"
            + "\n"
            + "ENTER \"B\" TO GO BACK TO MENU\n"
            + "\n"
            + "Enter the index of the portfolio you wanna calculate "
            + "values for from the above pics and B to go back to menu\n"
            + "\n"
            + " Portfolio selected\n"
            + "\n"
            + "********* Welcome to SINGLE PORTFOLIO PAGE **********\n"
            + "Name: Portfolio 1\n"
            + "Stocks in Portfolio: \n"
            + "Name: AAPL\n"
            + "Total stocks Owned: 5\n"
            + "Date Bought: 2000-01-04\n"
            + "Price: 101.19\n"
            + "\n"
            + "\n"
            + "********* Welcome to CALCULATE VALUE PAGE **********\n"
            + "\n"
            + " PRESS 1 FOR COST BASIS\n"
            + "PRESS 2 FOR PORTFOLIO VALUE\n"
            + " PRESS B TO GO BACK\n"
            + "\n"
            + "Enter Year you wanna calculate for\n"
            + "\n"
            + "Enter Month you wanna calculate for\n"
            + "\n"
            + "Enter day you wanna calculate for\n"
            + "\n"
            + "THE PORTFOLIO VALUE OF THIS PORTFOLIO IS 929.6500000000001\n"
            + "\n"
            + "********* Welcome to CALCULATE VALUE PAGE **********\n"
            + "\n"
            + " PRESS 1 FOR COST BASIS\n"
            + "PRESS 2 FOR PORTFOLIO VALUE\n"
            + " PRESS B TO GO BACK\n"
            + "\n"
            + "********* Welcome to DISPLAY ALL PORTFOLIO **********\n"
            + "1. Name: Portfolio 1\n"
            + "Stocks in Portfolio: \n"
            + "Name: AAPL\n"
            + "Total stocks Owned: 5\n"
            + "Date Bought: 2000-01-04\n"
            + "Price: 101.19\n"
            + "\n"
            + "\n"
            + "\n"
            + "ENTER \"B\" TO GO BACK TO MENU\n"
            + "\n"
            + "Enter the index of the portfolio you wanna calculate "
            + "values for from the above pics and B to go back to menu\n"
            + "\n"
            + "********* Welcome to Stock Market Simulator **********\n"
            + "1 .createPortfolio\n"
            + "2 .displayAllPortfolio\n"
            + "3 .editPortfolio\n"
            + "4 .calculateValue\n"
            + "5 .exit\n"
            + "PRESS THE MENU OPTION YOU DESIRE\n"
            + "\n"
            + "Thank you for using the application.", out.toString());
  }


}